
abstract class HomeCubitStates {}
class InitialHomeState extends HomeCubitStates{}
class UpdateNavBarIndexState extends HomeCubitStates{}
class LoadingTasksState extends HomeCubitStates{}
class EmptyTasksState extends HomeCubitStates{}
class BottomSheetOpened extends HomeCubitStates{}
class BottomSheetClosed extends HomeCubitStates{}
class LoadingInsertedDataBase extends HomeCubitStates{}
class DoneInsertedDataBase extends HomeCubitStates{}
class ErrorInsertedDataBase extends HomeCubitStates{}
class LoadingDeleteDataBaseElement extends HomeCubitStates{}
class DoneDeleteDataBaseElement extends HomeCubitStates{}
class ErrorDeleteDataBaseElement extends HomeCubitStates{}
class LoadingUpdateDataBaseElement extends HomeCubitStates{}
class DoneUpdateDataBaseElement extends HomeCubitStates{}
class ErrorUpdateDataBaseElement extends HomeCubitStates{}
class DoneGetDataBase extends HomeCubitStates{}
class EmptyNewTasks extends HomeCubitStates{}
class EmptyDoneTasks extends HomeCubitStates{}
class EmptyArchivedTasks extends HomeCubitStates{}
class LoadingGetDataBase extends HomeCubitStates{}
class ErrorGetDataBase extends HomeCubitStates{}
class SuccessfulDataBaseTransaction extends HomeCubitStates{}
class ErrorDataBaseTransaction extends HomeCubitStates{}
